import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollSection from "./componets/scrollanimation/Scrollanimation";
import ProfessionalCursor from "./componets/professional-cursor/professional-cursor";
import Footer from "./componets/layout/Footer";
import Header from "./componets/layout/Header";
import ScrollanimationHead from "./componets/scrollanimation/ScrollanimationHead";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} bg-primery ${geistMono.variable} antialiased`}>
        <Header />
        <ProfessionalCursor />
        {children}
        <ScrollSection>
          <Footer />
        </ScrollSection>
      </body>
    </html>
  );
}
